### ISSUE TITLE
Include the dependecies with the plugin

### ISSUE THREAD

**Issue by maforget** [killo3967/Find-Comics-by-image-types-Comicrack-smartlist-plugin-#3]
Instead of asking to copy the libraries you could simply include them with your plugin in the same folder. You can check [my plugin](https://github.com/maforget/Bedetheque-Scrapper-2) to see an example. 

I was able to make your plugin work, by copying the following files:, I've attached them for ease, just drop them in your plugin folder.

```
_abcoll.py
_weakrefset.py
abc.py
collections.py
fnmatch.py
genericpath.py
heapq.py
io.py
keyword.py
linecache.py
list.txt
ntpath.py
os.py
shutil.py
stat.py
string.py
struct.py
types.py
UserDict.py
warnings.py
zipfile.py
```
[dependencies.zip](https://github.com/killo3967/Find-Comics-by-image-types-Comicrack-smartlist-plugin-/files/11861232/dependencies.zip)

**Comment by killo3967** [comment]
Done to next version

**Comment by killo3967** [comment]
Done. Thanks very much.

**Comment by killo3967** [comment]
.
